### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by phlegx** [megurock/vue-intersect-directive#6]
Using this package with an SSR environment results in an error. Please remove `window` from code.

```js
if (window.Vue) {
    Vue.use(VueIntersect.install);
}
```

See: https://github.com/megurock/vue-intersect-directive/blob/master/src/index.ts#L18

**Comment by megurock** [comment]
@phlegx 
Thank you for the comment. I hope this will resolve the situation.
https://github.com/megurock/vue-intersect-directive/pull/8
